version: '3.9'
volumes:
  aixadadb:
networks:
  aixada:
    driver: bridge
services:
  mariadb:
    image: 'mariadb:10.6'
    networks:
      - aixada
    ports:
      - '3306:3306'
    volumes:
      - 'aixadadb:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_DATABASE=aixada
      - MARIADB_USER=aixada
      - MARIADB_PASSWORD=aixada
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_general_ci
  phpmyadmin:
    image: 'phpmyadmin:5'
    depends_on:
      - mariadb
    networks:
      - aixada
    ports:
      - '8084:80'
    links:
      - 'mariadb:database'
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=64M
  php:
    build: .
    depends_on:
      - mariadb
    networks:
      - aixada
    ports:
      - '8083:80'
    links:
      - 'mariadb:database'
    volumes:
      - '.:/var/www/html'
