version: '3.9'
volumes:
  aixadadb:
networks:
  aixada:
    driver: bridge
services:
  mysql:
    image: 'mysql:8.0'
    networks:
      - aixada
    ports:
      - '3307:3306'
    volumes:
      - 'aixadadb:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aixada
      - MYSQL_USER=aixada
      - MYSQL_PASSWORD=aixada
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    depends_on:
      - mysql
    networks:
      - aixada
    ports:
      - '8082:80'
    links:
      - 'mysql:database'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
  php:
    build: .
    depends_on:
      - mysql
    networks:
      - aixada
    ports:
      - '8083:80'
      - '8443:443'
    links:
      - 'mysql:database'
    volumes:
      - '.:/var/www/html'
