<?php

/**
 * Helper functions for the negative balances feature.
 * Controls whether users with negative account balances are blocked from certain pages.
 *
 * @package Aixada
 */

/**
 * Returns whether the negative balances feature is enabled for this instance.
 *
 * @return bool
 */
function allowed_negative_balances()
{
    return isset(configuration_vars::get_instance()->allow_negative_balances) && configuration_vars::get_instance()->allow_negative_balances === true;
}

/**
 * Returns the grace period in days before a negative balance triggers a block.
 * Defaults to 14 days if not set in config.
 *
 * @return int
 */
function negative_balances_grace_periode()
{
    return isset(configuration_vars::get_instance()->negative_balances_grace_periode) ? (int) configuration_vars::get_instance()->negative_balances_grace_periode : 14;
}

/**
 * Returns the list of pages where the negative balance block is enforced.
 * Pages not in this list are accessible regardless of account balance.
 *
 * @return array List of PHP filenames (e.g. ['shop_and_order.php']).
 */
function get_negative_balances_disabled_pages()
{
    return isset(configuration_vars::get_instance()->negative_balances_disabled_pages) ? configuration_vars::get_instance()->negative_balances_disabled_pages : array();
}

/**
 * Returns the inline JS for the negative balance check on enforced pages.
 * Uses output buffering to capture the JS generated by negativeBalances.js.php.
 * Returns null if the current page is not in the disabled pages list.
 *
 * @return string|null HTML script block, or null if not applicable.
 */
function include_negative_balances_js()
{
    $disabled_pages = get_negative_balances_disabled_pages();
    if (in_array(substr($_SERVER['SCRIPT_NAME'], 1), $disabled_pages)) {
        ob_start();
        require('js/aixadautilities/negativeBalances.js.php');
        $script = ob_get_contents();
        ob_end_clean();
        return $script;
    }
}

/**
 * Returns a CSS class to hide page content on enforced pages until the
 * negative balance JS check has run.
 *
 * @return string 'hidden' if on an enforced page, '' otherwise.
 */
function negative_balances_stagewrap_class()
{
    $disabled_pages = get_negative_balances_disabled_pages();
    return in_array(substr($_SERVER['SCRIPT_NAME'], 1), $disabled_pages) ? 'hidden' : '';
}
